use phf::{phf_map, phf_set};
use super::Instruction; 
use super::GroupType;
use super::{ASTElement, Node, Tree};

/// Struct for lexing BBCode Instructions into an ASTElement tree.
pub struct BBCodeLexer {
	current_node: ASTElement,
	anchor: Tree<Node<ASTElement>>,
	next_text_as_arg: Option<fn(&mut BBCodeLexer, &str)>,
	ignore_tags: Option<&'static str>,
	ignore_formatting: bool,
	linebreaks_allowed: bool,
	preserve_empty: bool
}
impl BBCodeLexer {
	/// Creates a new BBCodeLexer.
	pub fn new(preserve_empty: bool) -> BBCodeLexer {
		BBCodeLexer {
			anchor: Tree::new(),
			current_node: ASTElement::new(GroupType::Document),
			next_text_as_arg: None,
			ignore_tags: None,
			ignore_formatting: false,
			linebreaks_allowed: true,
			preserve_empty
		}
	}
	/// Lexes a vector of Instructions.
	pub fn lex(&mut self, instructions: &[Instruction]) -> &Tree<Node<ASTElement>> {
		&self.anchor
	}
	/// Matches Instruction types.
	fn execute(&mut self, instruction: &Instruction) {
		
	}
	/// Creates a new ASTElement.
	fn new_group(&mut self, ele_type: GroupType) {
		
	}

	
	fn end_group(&mut self, ele_type: GroupType) {
		
	}

}
/// Static compile-time map of tags without arguments to lexer commands.
static NO_ARG_CMD: phf::Map<&'static str, fn(&mut BBCodeLexer)> = phf_map! {
    
};
/// Static compile-time map of tags with single arguments to lexer commands.
static ONE_ARG_CMD: phf::Map<&'static str, fn(&mut BBCodeLexer, &str)> = phf_map! {
   
};
/// Static compile-time set of valid HTML web colours.
static WEB_COLOURS: phf::Set<&'static str> = phf_set! {
	"aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgrey",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "grey",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred ",
    "indigo ",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgrey",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "transparant",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
    "Aliceblue",
    "Antiquewhite",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "Blanchedalmond",
    "Blue",
    "Blueviolet",
    "Brown",
    "Burlywood",
    "Cadetblue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "Cornflowerblue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "Darkblue",
    "Darkcyan",
    "Darkgoldenrod",
    "Darkgray",
    "Darkgrey",
    "Darkgreen",
    "Darkkhaki",
    "Darkmagenta",
    "Darkolivegreen",
    "Darkorange",
    "Darkorchid",
    "Darkred",
    "Darksalmon",
    "Darkseagreen",
    "Darkslateblue",
    "Darkslategray",
    "Darkslategrey",
    "Darkturquoise",
    "Darkviolet",
    "Deeppink",
    "Deepskyblue",
    "Dimgray",
    "Dimgrey",
    "Dodgerblue",
    "Firebrick",
    "Floralwhite",
    "Forestgreen",
    "Fuchsia",
    "Gainsboro",
    "Ghostwhite",
    "Gold",
    "Goldenrod",
    "Gray",
    "Grey",
    "Green",
    "Greenyellow",
    "Honeydew",
    "Hotpink",
    "Indianred ",
    "Indigo ",
    "Ivory",
    "Khaki",
    "Lavender",
    "Lavenderblush",
    "Lawngreen",
    "Lemonchiffon",
    "Lightblue",
    "Lightcoral",
    "Lightcyan",
    "Lightgoldenrodyellow",
    "Lightgray",
    "Lightgrey",
    "Lightgreen",
    "Lightpink",
    "Lightsalmon",
    "Lightseagreen",
    "Lightskyblue",
    "Lightslategray",
    "Lightslategrey",
    "Lightsteelblue",
    "Lightyellow",
    "Lime",
    "Limegreen",
    "Linen",
    "Magenta",
    "Maroon",
    "Mediumaquamarine",
    "Mediumblue",
    "Mediumorchid",
    "Mediumpurple",
    "Mediumseagreen",
    "Mediumslateblue",
    "Mediumspringgreen",
    "Mediumturquoise",
    "Mediumvioletred",
    "Midnightblue",
    "Mintcream",
    "Mistyrose",
    "Moccasin",
    "Navajowhite",
    "Navy",
    "Oldlace",
    "Olive",
    "Olivedrab",
    "Orange",
    "Orangered",
    "Orchid",
    "Palegoldenrod",
    "Palegreen",
    "Paleturquoise",
    "Palevioletred",
    "Papayawhip",
    "Peachpuff",
    "Peru",
    "Pink",
    "Plum",
    "Powderblue",
    "Purple",
    "Rebeccapurple",
    "Red",
    "Rosybrown",
    "Royalblue",
    "Saddlebrown",
    "Salmon",
    "Sandybrown",
    "Seagreen",
    "Seashell",
    "Sienna",
    "Silver",
    "Skyblue",
    "Slateblue",
    "Slategray",
    "Slategrey",
    "Snow",
    "Springgreen",
    "Steelblue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Transparant",
    "Violet",
    "Wheat",
    "White",
    "Whitesmoke",
    "Yellow",
    "Yellowgreen"
};

/// Static compile-time set of accepted image types.
static ACCEPTED_IMAGE_TYPES: phf::Set<&'static str> = phf_set! {
	".jpg",
	".jpeg",
	".pjpeg",
	".pjp",
	".jfif",
	".png",
	".apng",
	".gif",
	".bmp",
	//".svg", Dangerous!
	".webp",
};

/// Static compile-time set of forbidden URL characters.
static FORBIDDEN_URL_CHARS: phf::Set<char> = phf_set! {
	':',
	';',
	'*',
	'#',
	'{',
	'}',
	'|',
	'^',
	'~',
	'[',
	']',
	'`',
};

/// Static compile-time set of accepted list types.
static LIST_TYPES: phf::Set<&'static str> = phf_set! {
	"1",
	"a",
	"A",
	"i",
	"I",
	"circle",
	"square",
	"none",
};

/// A simplified representation of an element used when closing and reopening groups.
pub struct GroupShorthand {
	pub ele_type: GroupType,
	pub arg: Option<String>
}